org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
org.gradle.jvmargs=-Xmx4g
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.offline=false

# Project Properties
GROUP=dev.samstevens.totp
VERSION_NAME=1.7.2

# POM Properties
POM_NAME=java-totp
POM_DESCRIPTION=A library to help implement time-based one time passwords to enable MFA
POM_INCEPTION_YEAR=2021
POM_URL=https://github.com/samdjstevens/java-totp

# License Properties
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=http://www.opensource.org/licenses/mit-license.php
POM_LICENSE_DIST=repo

# SCM Properties
POM_SCM_URL=https://github.com/samdjstevens/java-totp
POM_SCM_CONNECTION=scm:git:git://github.com/samdjstevens/java-totp.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/samdjstevens/java-totp.git

# Developer
POM_DEVELOPER_NAME=Sam Stevens
POM_DEVELOPER_EMAIL=samdjstevens@googlemail.com
POM_DEVELOPER_URL=https://github.com/samdjstevens
